//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TamweelyMobileApp.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TamweelyResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TamweelyResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TamweelyMobileApp.Resx.TamweelyResources", typeof(TamweelyResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue?.
        /// </summary>
        internal static string _continue {
            get {
                return ResourceManager.GetString("continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string account {
            get {
                return ResourceManager.GetString("account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been deleted successfully.
        /// </summary>
        internal static string account_deleted {
            get {
                return ResourceManager.GetString("account_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Lease.
        /// </summary>
        internal static string al {
            get {
                return ResourceManager.GetString("al", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Lease should be greater than 0.
        /// </summary>
        internal static string al_error {
            get {
                return ResourceManager.GetString("al_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        internal static string alert {
            get {
                return ResourceManager.GetString("alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account ?.
        /// </summary>
        internal static string Already_have_an_account {
            get {
                return ResourceManager.GetString("Already_have_an_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The remaining installment amount is not enough to have autolease, please contact your bank.
        /// </summary>
        internal static string amount_not_enough {
            get {
                return ResourceManager.GetString("amount_not_enough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string apply {
            get {
                return ResourceManager.GetString("apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic.
        /// </summary>
        internal static string Arabic {
            get {
                return ResourceManager.GetString("Arabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to balance amount.
        /// </summary>
        internal static string balance_amount {
            get {
                return ResourceManager.GetString("balance_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is an approximate calculation, for accurate installment balance you should contact your bank..
        /// </summary>
        internal static string balance_claim {
            get {
                return ResourceManager.GetString("balance_claim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Value.
        /// </summary>
        internal static string car_value {
            get {
                return ResourceManager.GetString("car_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car value can not be greater than 50000.
        /// </summary>
        internal static string car_value_error {
            get {
                return ResourceManager.GetString("car_value_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card Limit.
        /// </summary>
        internal static string cc {
            get {
                return ResourceManager.GetString("cc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit card limit can not be less than zero.
        /// </summary>
        internal static string cc_error {
            get {
                return ResourceManager.GetString("cc_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit card limit should be greater than 0.
        /// </summary>
        internal static string cc_error_zero {
            get {
                return ResourceManager.GetString("cc_error_zero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Language.
        /// </summary>
        internal static string ChooseLanguage {
            get {
                return ResourceManager.GetString("ChooseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About to sign out from the app, Continue?.
        /// </summary>
        internal static string confirm {
            get {
                return ResourceManager.GetString("confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete your account?.
        /// </summary>
        internal static string confirm_delete {
            get {
                return ResourceManager.GetString("confirm_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete&amp;#10;Account.
        /// </summary>
        internal static string delete_account {
            get {
                return ResourceManager.GetString("delete_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did not received the code ?.
        /// </summary>
        internal static string Did_not_received_the_code {
            get {
                return ResourceManager.GetString("Did_not_received_the_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don’t have an account ? .
        /// </summary>
        internal static string Dont_have_an_account {
            get {
                return ResourceManager.GetString("Dont_have_an_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down Payment (sar).
        /// </summary>
        internal static string down_payment {
            get {
                return ResourceManager.GetString("down_payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down Payment (%).
        /// </summary>
        internal static string down_payment_perc {
            get {
                return ResourceManager.GetString("down_payment_perc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile.
        /// </summary>
        internal static string edit_profile {
            get {
                return ResourceManager.GetString("edit_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter pin code to verify!.
        /// </summary>
        internal static string enter_code {
            get {
                return ResourceManager.GetString("enter_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter name!.
        /// </summary>
        internal static string enter_name {
            get {
                return ResourceManager.GetString("enter_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string filter {
            get {
                return ResourceManager.GetString("filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High to Low.
        /// </summary>
        internal static string high_to_low {
            get {
                return ResourceManager.GetString("high_to_low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installment.
        /// </summary>
        internal static string installment {
            get {
                return ResourceManager.GetString("installment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance (sar).
        /// </summary>
        internal static string insurance {
            get {
                return ResourceManager.GetString("insurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance (%).
        /// </summary>
        internal static string insurance_perc {
            get {
                return ResourceManager.GetString("insurance_perc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interest (sar).
        /// </summary>
        internal static string interest {
            get {
                return ResourceManager.GetString("interest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interest (%).
        /// </summary>
        internal static string interest_perc {
            get {
                return ResourceManager.GetString("interest_perc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid phone number!.
        /// </summary>
        internal static string invalid_phone {
            get {
                return ResourceManager.GetString("invalid_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Changed.
        /// </summary>
        internal static string LanguageChanged {
            get {
                return ResourceManager.GetString("LanguageChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Payment (sar).
        /// </summary>
        internal static string last_payment {
            get {
                return ResourceManager.GetString("last_payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Payment (%).
        /// </summary>
        internal static string last_payment_perc {
            get {
                return ResourceManager.GetString("last_payment_perc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan amount can&apos;t be more than 500000. Please increase the down payment..
        /// </summary>
        internal static string lease_error {
            get {
                return ResourceManager.GetString("lease_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        internal static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low to High.
        /// </summary>
        internal static string low_to_high {
            get {
                return ResourceManager.GetString("low_to_high", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make.
        /// </summary>
        internal static string make {
            get {
                return ResourceManager.GetString("make", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mortgage Loan.
        /// </summary>
        internal static string ml {
            get {
                return ResourceManager.GetString("ml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mortgage Loan should be greater than 0.
        /// </summary>
        internal static string ml_error {
            get {
                return ResourceManager.GetString("ml_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile No.
        /// </summary>
        internal static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Verification.
        /// </summary>
        internal static string Mobile_Verification {
            get {
                return ResourceManager.GetString("Mobile_Verification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not change mobile number because this is your username.
        /// </summary>
        internal static string MobileClaim {
            get {
                return ResourceManager.GetString("MobileClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Installment.
        /// </summary>
        internal static string monthly_installment {
            get {
                return ResourceManager.GetString("monthly_installment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. of Months.
        /// </summary>
        internal static string no_of_months {
            get {
                return ResourceManager.GetString("no_of_months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no vehicles that falls in your available balance limit. Please go back and change the inputs..
        /// </summary>
        internal static string no_vehicles {
            get {
                return ResourceManager.GetString("no_vehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Loan.
        /// </summary>
        internal static string pl {
            get {
                return ResourceManager.GetString("pl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Loan should be greater than 0.
        /// </summary>
        internal static string pl_error {
            get {
                return ResourceManager.GetString("pl_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the 4 digit OTP code sent on.
        /// </summary>
        internal static string Please_enter_the_4_digit_OTP_code_sent_on {
            get {
                return ResourceManager.GetString("Please_enter_the_4_digit_OTP_code_sent_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        internal static string privacy_policy {
            get {
                return ResourceManager.GetString("privacy_policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide the following details to calculate your remaining installment.
        /// </summary>
        internal static string provide_detail {
            get {
                return ResourceManager.GetString("provide_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your remaining installment amount is.
        /// </summary>
        internal static string remaining_amount {
            get {
                return ResourceManager.GetString("remaining_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend Now.
        /// </summary>
        internal static string Resend_Now {
            get {
                return ResourceManager.GetString("Resend_Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string reset {
            get {
                return ResourceManager.GetString("reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary.
        /// </summary>
        internal static string salary {
            get {
                return ResourceManager.GetString("salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary should be greater than 0.
        /// </summary>
        internal static string salary_error {
            get {
                return ResourceManager.GetString("salary_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAR.
        /// </summary>
        internal static string sar {
            get {
                return ResourceManager.GetString("sar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a language!.
        /// </summary>
        internal static string select_language {
            get {
                return ResourceManager.GetString("select_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        internal static string SelectedLanguage {
            get {
                return ResourceManager.GetString("SelectedLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string Sign_Up {
            get {
                return ResourceManager.GetString("Sign_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signin Now.
        /// </summary>
        internal static string Signin_Now {
            get {
                return ResourceManager.GetString("Signin_Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signup Now.
        /// </summary>
        internal static string SignupNow {
            get {
                return ResourceManager.GetString("SignupNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong, Please try again later!.
        /// </summary>
        internal static string something {
            get {
                return ResourceManager.GetString("something", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort.
        /// </summary>
        internal static string sort {
            get {
                return ResourceManager.GetString("sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to success.
        /// </summary>
        internal static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms and Conditions.
        /// </summary>
        internal static string terms {
            get {
                return ResourceManager.GetString("terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Price.
        /// </summary>
        internal static string total_price {
            get {
                return ResourceManager.GetString("total_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicles.
        /// </summary>
        internal static string vehicles {
            get {
                return ResourceManager.GetString("vehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Vehicles.
        /// </summary>
        internal static string view_vehicles {
            get {
                return ResourceManager.GetString("view_vehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa / Master.
        /// </summary>
        internal static string vm {
            get {
                return ResourceManager.GetString("vm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Balance.
        /// </summary>
        internal static string your_balance {
            get {
                return ResourceManager.GetString("your_balance", resourceCulture);
            }
        }
    }
}
